name: Curl table

on:
  schedule:
    - cron:  '30 5,17 * * *'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
  workflow_dispatch:

jobs:
  run_tests:
    runs-on: ubuntu-20.04
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: Clone
      run: |        
        git ls-files
        git remote show origin https://github.com/Risenes/letter2.0 .
        git config --global user.email "risenes@gmail.com"
        git config --global user.name "Risenes"
    - name: Load table and commit
      run: |-  
        curl https://docs.google.com/spreadsheets/d/1d6E9VREMtVGHdYubZoZs5fmS2P7tCi6w47LjDdylphE/gviz/tq?tqx=out:csv&sheet=generator | jq . > table1.csv
    - uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: table1.csv
