name: Curl table

on:
  schedule:
    - cron:  '30 5,17 * * *'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
  workflow_dispatch:

jobs:
  run_tests:
    runs-on: ubuntu-20.04
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: Download Feed
      run: |-
        curl https://docs.google.com/spreadsheets/d/1d6E9VREMtVGHdYubZoZs5fmS2P7tCi6w47LjDdylphE/gviz/tq?tqx=out:csv&sheet=generator | jq . > table.csv
    - name: Commit and push changes
      run: |-
        git diff
        git --global user.name "Risenes"
        git --global user.email "risenes@gmail.com"
        git diff --quiet || (git add -A && git commit -m "Updated with latest")
        git push
