name: Curl table

on:
  schedule:
    - cron:  '30 5,17 * * *'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
  workflow_dispatch:

jobs:
  run_tests:
    runs-on: ubuntu-20.04
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: wget
      uses: wei/wget@v1
      with:
        args: -O table.csv https://docs.google.com/spreadsheets/d/1d6E9VREMtVGHdYubZoZs5fmS2P7tCi6w47LjDdylphE/gviz/tq?tqx=out:csv&sheet=generator
    - name: Load table and commit
      run: |-  
        git add table1.csv
        git branch -u origin/main
        git commit -m "Update table by bot"
        
    - name: Push changes # push the output folder to your repo
      uses: ad-m/github-push-action@master
      with: 
        
        github_token: ${{ secrets.LETTER }}
        force: true
